name: API Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Run API tests
        run: dotnet test /home/runner/work/lesson_32/lesson_32/tests/Library.Tests.Api/Library.Tests.Api.csproj --logger "trx;LogFileName=test_results.trx" --results-directory /home/runner/work/lesson_32/lesson_32/tests/Library.Tests.Ui/bin/Debug/net8.0/test-results

      # Upload test results as artifacts
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: /home/runner/work/lesson_32/lesson_32/tests/Library.Tests.Ui/bin/Debug/net8.0/test-results

  test-results:
    name: Test Results
    runs-on: ubuntu-latest
    needs: run-api-tests
    steps:
      # Display test results using dorny/test-reporter
      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always() # Always run this step, even if previous steps fail
        with:
          artifact: test-results
          name: Api Tests Results
          path: 'test_results.xml'
          reporter: dotnet-trx
          fail-on-error: false